spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms
    username: lakshman
    password: lakshman


  jpa:
    show-sql: true
    properties:
     hibernate.format_sql: true
server.port: 8090       